default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: back_development

test:
  <<: *default
  database: back_test

production:
  <<: *default
  database: back_production
  username: back
  password: <%= ENV['BACK_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: back_production
  username: back
  password: <%= ENV['BACK_DATABASE_PASSWORD'] %>